version: "3.8"

services:
  uptime-kuma:
    build: .
    container_name: uptime-kuma
    restart: always
    volumes:
      - ./data/uptime-kuma-data:/app/data
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=sqlite:/app/data/uptime-kuma.db

volumes:
    data:
